<?php

namespace Foundation\Requests\Frontend;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Class CommentStoreRequest
 * @package Foundation\Requests\Frontend
 */
class CommentStoreRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'full_name' => 'required|max:60',
            'email'     => 'required|email|max:60',
            'website'   => 'sometimes|nullable|max:50',
            'comment'   => 'required|max:350',
            'signature' => 'required',
            'post_id'   => 'required|exists:posts,id'
        ];
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

}
