<?php

namespace Foundation\Models;

use Kiranti\Supports\Cache\Cacheable;
use Kiranti\Supports\BaseModel as Model;

/**
 * Class Setting
 * @package Foundation\Models
 */
class Setting extends Model
{

    use Cacheable;

    protected $cacheKey = 'settings';

    protected $cacheAll = true;

    protected $individualCache = true;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'key', 'value', 'updated_by'
    ];

    public function update(array $attributes = [], array $options = [])
    {
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

}
